### ISSUE TITLE
Split the library into smaller parts

### ISSUE THREAD

**Issue by lubomir** [release-engineering/kobo#121]
There are many modules in this library, some of which bring lots of dependencies like koji or django. It would be nice to split the library into multiple smaller libraries so that people can install only what they need.

This is already done to some level in Fedora RPM packaging with subpackages:

    kobo
        kobo-admin
        python3-kobo
        python3-kobo-admin
        python3-kobo-client
        python3-kobo-django
        python3-kobo-hub
        python3-kobo-rpmlib
        python3-kobo-worker

For example in Pungi we use only these modules: log, pkgset, rpmlib, shortcuts and threads. No Django needed, yet when installing with pip during development, it gets pulled in.

**Comment by rohanpm** [comment]
I think this is the same as https://github.com/release-engineering/kobo/issues/77 - closing as duplicate.
