### ISSUE TITLE
Py2-only dependency: krbV

### ISSUE THREAD

**Issue by yontalcar** [release-engineering/kobo#130]
kobo depends on [python-krbV](https://pypi.org/project/python-krbV/), which is python2-only and dead. We need to use something else to be able to use dependent functionality on Python 3.

**Comment by alexandrevicenzi** [comment]
@yontalcar do you have any suggestion of a library to replace it?

Perhaps [gssapi](https://pypi.org/project/gssapi/) could do the job.

**Comment by yontalcar** [comment]
yeah, it should be able to do the trick

**Comment by alexandrevicenzi** [comment]
@yontalcar fell free to send a PR with this fix :)
