### ISSUE TITLE
Enhancement: add a --profile option

### ISSUE THREAD

**Issue by rhjostone** [release-engineering/kobo#147]
As I understand it, Kobo supports loading configuration values from a file:

https://github.com/release-engineering/kobo/blob/7500cd7daaba44e38db1efd98175689377be14b1/kobo/conf.py#L111

And the extent of runtime configuration for a (global) profile is generally implemented through environment variables in a downstream client:

https://github.com/release-engineering/kobo/blob/7500cd7daaba44e38db1efd98175689377be14b1/kobo/client/__init__.py#L35

Users would have to write wrapper scripts to ensure the correct profile is set if using this approach.

Could configuration profiles be implemented as a CLI option? The option could look like this:

```
$ downstream-kobo-client --help
Usage: downstream-kobo-client <command> [args] [--help]

Options:
  -h, --help           show this help message and exit
  --username=USERNAME  specify user
  --password=PASSWORD  specify password
  --profile=PROFILE    specify profile
```

Which could run like this:

```
$ downstream-kobo-client --profile=${PROFILE}
```

And this in turn could look in a designated configuration folder like so:

```
/etc/downstream-kobo-client/${PROFILE}.conf
```

**Comment by rohanpm** [comment]
Released in kobo 0.18.0.
