### ISSUE TITLE
Restrict access to user list/detail view

### ISSUE THREAD

**Issue by rhyw** [release-engineering/kobo#209]
The kobo user/list is by default public, this could be an issue for apps using it(failed to meet the ESS compliance requirements).

Preferably to add a separate configurable option, i.e., to allow configure access to user list/detail to admin / authenticated user/ anonymously(the default for backward compatibility).

**Comment by rhyw** [comment]
I appearantly missed the `MenuItem` inline doc, there's `acl_perms` that could probably help. I'll check if it works.

**Comment by rhyw** [comment]
By specifying `acl_perms`, the corresponding menu entry is indeed invisible!

However problem persists. e.g., I tweak the menu item with below parameters:
```
MenuItem("Users", "user/list", None, ("view_user",)),
```
From WebUI, the `Users` is gone, but manually typing in `url`(aka `reverse('user/list')`), both user list / user details could still be seen because backend views have no permission control at all.

Thus I guess this issue is still valid.

**Comment by kdudka** [comment]
Yes, hiding the item from menu is not a solution really.
