### ISSUE TITLE
Kobo release on PyPI is very old

### ISSUE THREAD

**Issue by pbabinca** [release-engineering/kobo#24]
Please update kobo release on PyPI to match upstream one.

Latest [kobo release on PyPI](https://pypi.python.org/pypi/kobo): 0.3.8
Latest upstream release: 0.5.2

**Comment by TomasTomecek** [comment]
this can be easily automated with travis CI

**Comment by ktdreyer** [comment]
We don't have control over the PyPI entry yet. See https://sourceforge.net/p/pypi/support-requests/632/

**Comment by ktdreyer** [comment]
I have added @lubomir as an Owner to the kobo PyPI entry.

**Comment by lubomir** [comment]
`pip install kobo` should now install 0.5.2
