### ISSUE TITLE
Extend the hub.models.Task to store user-specified additional metadata

### ISSUE THREAD

**Issue by rhyw** [release-engineering/kobo#263]
As subject. Preferably with json format. Benefits includes to allow filtering of tasks based on metadata / pipeline integration etc. Currently there is `comment` field that allows some random text, which seems to have limited filtering capabilities.

I'm filing this issue to see if there's any objection of this? If it's not an option, I'd have to extend the models in our app that depend on kobo's `Task` model.

See also: https://issues.redhat.com/browse/OSH-567 for a more detailed use case.

@rohanpm  @kdudka  @lzaoral any objections to this?

**Comment by kdudka** [comment]
@rhyw Why cannot you put the data into `args`, which is a JSON serialized dictionary already?  https://github.com/release-engineering/kobo/blob/1ac403461947289c2eae8b197d1a3e51e1d487b6/kobo/hub/models.py#L560

> See also: https://issues.redhat.com/browse/OSH-567 for a more detailed use case.

Let's be transparent.  Such links cannot be accessed by community members who are not Red Hat employees.

**Comment by rhyw** [comment]
I'll avoid pasting internal links here in future, thanks for the reminder.

I was aware of the `args` field earlier, however after a quick look I thought that metadata don't fit to any existing keys in `args`.

I checked it again, we could definitely add a new key to store the metadata specified from the command line. I'll mark this as closed, thanks!
