### ISSUE TITLE
kobo auth migrations/model conflict with django.contrib.auth

### ISSUE THREAD

**Issue by rohanpm** [release-engineering/kobo#34]
With Django 1.8, starting with an empty database, with INSTALLED_APPS containing 'django.contrib.auth' and 'kobo.django.auth', manage.py migrate will fail with:

> ERRORS:
> auth.User.groups: (fields.E304) Reverse accessor for 'User.groups' clashes with reverse accessor for 'User.groups'.
> 	HINT: Add or change a related_name argument to the definition for 'User.groups' or 'User.groups'.
> auth.User.user_permissions: (fields.E304) Reverse accessor for 'User.user_permissions' clashes with reverse accessor for 'User.user_permissions'.
> 	HINT: Add or change a related_name argument to the definition for 'User.user_permissions' or 'User.user_permissions'.
> kobo_auth.User.groups: (fields.E304) Reverse accessor for 'User.groups' clashes with reverse accessor for 'User.groups'.
> 	HINT: Add or change a related_name argument to the definition for 'User.groups' or 'User.groups'.
> kobo_auth.User.user_permissions: (fields.E304) Reverse accessor for 'User.user_permissions' clashes with reverse accessor for 'User.user_permissions'.
> 	HINT: Add or change a related_name argument to the definition for 'User.user_permissions' or 'User.user_permissions'.

It is possible to silence this by use of SILENCED_SYSTEM_CHECKS, but then migrations will fail because both apps try to create the table for the Users model.

It's unclear how to make this work; the migration in kobo.django.auth doesn't create related tables such as Groups.  So, disabling the migrations from django.contrib.auth doesn't work (the User.username field will be left at the default 30 chars, defeating the purpose of kobo_auth's User) and disabling the migrations from django.contrib.auth doesn't work (kobo's migrations will fail to create necessary tables).

**Comment by rohanpm** [comment]
Need to review what's the status of this after commits 363c03c4e5cf2eb0, d7cc0b3c496d575.

**Comment by alexandrevicenzi** [comment]
@rohanpm this is fixed as long as you set `AUTH_USER_MODEL = 'kobo_auth.User'` in the project settings.

**Comment by rohanpm** [comment]
I'm withdrawing this issue:

- In comment above, Alex suggests it can be fixed by the projects using kobo
- If this is still a problem, I'm pretty sure ongoing Django 3.x porting work will rediscover this and result in an up-to-date report.
