### ISSUE TITLE
Support for Django 1.11

### ISSUE THREAD

**Issue by frenzymadness** [release-engineering/kobo#44]
Django 1.11 is next version with LTS and the last version with Python 2.7 support so Kobo should support it. Also, Django 1.8 EOL will be in April 2018.

https://www.djangoproject.com/download/

Related to: https://github.com/release-engineering/kobo/issues/2

**Comment by alexandrevicenzi** [comment]
Biggest changes to get Kobo running on 1.11 are:

- Drop Python 2.6
- Fix project settings
- Fix StateEnumField and JSONField from #2 
- Rewrite all routes because of `django.conf.urls.patterns` is gone since 1.9
- Fix ~25 broken test cases due to other minor changes in Django
