### ISSUE TITLE
Use Docker in Travis CI to avoid skipping tests

### ISSUE THREAD

**Issue by frenzymadness** [release-engineering/kobo#46]
Current Travis builds run in Ubuntu Trusty, where Koji is not available so tests which depend on RPM and Koji are skipped.

Possibilities:
- Use docker to run tests in Travis https://docs.travis-ci.com/user/docker/
- Wait until Travis switches to Ubuntu Xenial where Koji might be somehow available

**Comment by frenzymadness** [comment]
I tried to do it and it works!

How I did it:
1. I've created new Docker image called fedora-python-tox designed to run tox tests in Docker container with all available Pythons installed. See [github repo](https://github.com/frenzymadness/fedora-python-tox) and [docker hub](https://hub.docker.com/r/frenzymadness/fedora-python-tox/)
2. I've created one more Docker image (designed for Kobo testing) based on Docker image from point one. See Dockerfile in my new [docker branch](https://github.com/frenzymadness/kobo/tree/docker) and [docker hub](https://hub.docker.com/r/frenzymadness/kobo/)
3. Updated `.travis.yml` file to pull Docker image from point 2 and use it to run test via Tox inside this container. Successful build can be found [here](https://travis-ci.org/frenzymadness/kobo/builds/278340817)
4. As you can see in logs, Python 2.7 and Python 3.6 has no skipped tests.
5. Profit :smile: 

I can simply reproduce all the steps above or anybody can follow it to create a new Docker hub account, new repository for Kobo, then connecting it with Github and then the last two steps with Dockerfile and Travis configuration (obviously with different names ...).

What do you think about it?

**Comment by ktdreyer** [comment]
I've filed https://github.com/junaruga/rpm-py-installer/issues/131 to make it easier to `pip install koji` on Ubuntu.

**Comment by rohanpm** [comment]
This was marked closed due to PR #61 which fixes the skipped tests, but note that it didn't do this by using docker.  It was sufficient to add some extra steps to the Travis builds to install extra dependencies.
