### ISSUE TITLE
Which django versions are supported? Can it documented somewhere in Kobo?

### ISSUE THREAD

**Issue by tkdchen** [release-engineering/kobo#54]
Just two questions as per title. Thank you.

**Comment by rohanpm** [comment]
The versions which are tested by Travis CI can be seen at https://github.com/release-engineering/kobo/blob/master/tox.ini .  We may want to add more there and add them also to the README.

**Comment by rohanpm** [comment]
Closing:

- Above comment remains true.  The set of tested Django versions can be seen at https://github.com/release-engineering/kobo/blob/master/tox.ini.
- It might work also on other Django versions, but only the tested versions can be reasonably called "supported".
