### ISSUE TITLE
Worker.update_worker does not update attributes

### ISSUE THREAD

**Issue by alexandrevicenzi** [release-engineering/kobo#68]
`Worker.update_worker` call save but it does not set any variable, which is nonsense.

It should set worker attributes based on function parameters.

https://github.com/release-engineering/kobo/blob/master/kobo/hub/models.py#L253

Code should be:

```python
def update_worker(self, enabled, ready, task_count):
    """Update worker attributes. Return worker_info.

    Update only if data provided from a worker differs.
    """
    if (self.enabled, self.ready, self.task_count) != (enabled, ready, task_count):
        self.enabled = enabled
        self.ready = ready
        self.task_count = task_count
        self.save()

    return self.export()
```

**Comment by lzaoral** [comment]
I've looked at this in detail and, in fact, the method seems to work as expected.  Just the test and documentation need some tweaking.  `Worker.save()` automatically updates `self.ready` and `self.task_count` according to the actual database contents.  The `self.enabled` field can only be modified by the client or hub and this method us used to tell the worker that it has been disabled/enabled.

The arguments do not correspond to the values that should be set but to the actual state of the worker.  The method is used to:
1) Signal the hub that its worker state are not up-to-date forcing it to recompute them.
2) Tell the worker about its new state.

See #217.
