### ISSUE TITLE
unsuccesfull cancelling tasks in infinite loop

### ISSUE THREAD

**Issue by mareksabo** [release-engineering/kobo#8]
It happens when a running task has a child which is already in closed state and child should be interrupted. Interrupt happens if new patch is added to scan, so it tries to interrupt the parent repeatedly. However, the parent is trying to shut down the child which has already finished (esp. in closed state) and query is looking for opened task, which throws an exception. I think the best idea is to add condition when the query finds no results, and if the state of the task is in finished state, do not throw exception (maybe write something to log).

**Comment by TomasTomecek** [comment]
+1 on making the state transition valid when some child tasks already finished

**Comment by mareksabo** [comment]
Resolved by 12effa6.
